### ISSUE TITLE
Feature: add analytics tracking for error and events

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodCollective#112]
Once we go live we might want to track analytics.

- [ ] - should use sdk-v2 analytics provider
- [ ] - decide on which tracker to send error's to (can it fit into an existing subscription?)
- [x] - decide on which tracker to send events to (can it fit into an existing subscription?)

**Comment by L03TJ3** [comment]
@decentralauren @patpedrosa assigned you two to figure out our current subscription plans for eg. GA / posthog / amplitude / sentry etc and to determine priority

this is out of scope for dOrg so is for our own sprints

**Comment by L03TJ3** [comment]
@patpedrosa ah! yes it actually was :)

**Comment by decentralauren** [comment]
@L03TJ3 looks like this can be closed as GC was added to GC per the ticket Pat linked above.
